### ISSUE TITLE
Error when first running on iOS

### ISSUE THREAD

**Issue by macso-philipperivard** [thingsboard/flutter_thingsboard_app#46] opened 2023-11-12 23:31 UTC
I'm trying to run the ThingsBoard Flutter mobile app (on first run without any changes in the codebase), but I'm running into an issue: 

```
Xcode build done.                                            6.6s

Failed to build iOS app

Could not build the precompiled application for the device.

Error (Xcode): lib/core/context/tb_context.dart:53:14: Error: Too many

positional arguments: 1 allowed, but 3 found.




Error launching application on DEVICE_NAME.
```

**Comment by ybeshkarov** [comment] 2024-02-16 11:17
Hello @macso-philipperivard!

Please clarify if you have this issue with the latest code base.
Because I'm not able to reproduce it.

**Comment by macso-philipperivard** [comment] 2024-02-18 00:47
Hi @ybeshkarov , I think that it's not an issue anymore, but I do have a critical issue on the flutter_thingsboar_pe_app: https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/55

Is there any way you could help me with this?

**Comment by ybeshkarov** [comment] 2024-02-21 14:38
Hi @macso-philipperivard, thanks for your answer.
Closing this issue then.

**Closed by ybeshkarov** 2024-02-21 14:38 UTC
Labels: question
